drop table AGROSTG.PURE_DESPACHOS;
truncate table AGROSTG.PURE_DESPACHOS;


select *
from AGROSTG.PURE_DESPACHOS;

select to_char(last_ddl_time,'dd/mm/yyyy hh:mi:ss') from dba_objects where object_name = 'PURE_DESPACHOS'
;

CREATE TABLE AGROSTG.PURE_DESPACHOS
(
    ANO NUMBER,
    SEMANA NUMBER,
    PROCESADORA VARCHAR2(100 BYTE),
    CLIENTE VARCHAR2(100 BYTE),
    PRODUCTO VARCHAR2(100 BYTE),
    FECHA_DESPACHO DATE,
    TMS NUMBER,
    CONTAINER VARCHAR2(100 BYTE),
    BL VARCHAR2(100 BYTE),
    DISCHARGE_PORT VARCHAR2(100 BYTE),
    SHIPPING_LINE VARCHAR2(100 BYTE),
    ARRIVAL_DATE DATE,
    TIPO_DOC VARCHAR2(100 BYTE),
    NO_DOC VARCHAR2(100 BYTE),
    FECHA_DOC DATE,
    CODIGO_OC VARCHAR2(100 BYTE),
    PRECIO NUMBER,
    TOTAL_USD NUMBER,
    FECHA_PAGO DATE,
    FECHA_EFECTIVA DATE,
    ABONOS NUMBER,
    CONCEPTO_NC VARCHAR2(100 BYTE),
    PAST_DUE NUMBER,
    DIAS_CREDITO NUMBER
)
ORGANIZATION EXTERNAL (
  TYPE ORACLE_LOADER
  DEFAULT DIRECTORY google_sheets
  ACCESS PARAMETERS (
    RECORDS DELIMITED BY NEWLINE
    SKIP 1
    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
    MISSING FIELD VALUES ARE NULL
(
    ANO CHAR(4000),
    SEMANA CHAR(4000),
    PROCESADORA CHAR(4000),
    CLIENTE CHAR(4000),
    PRODUCTO CHAR(4000),
    FECHA_DESPACHO DATE "DD/MM/YYYY",
    TMS CHAR(4000),
    CONTAINER CHAR(4000),
    BL CHAR(4000),
    DISCHARGE_PORT CHAR(4000),
    SHIPPING_LINE CHAR(4000),
    ARRIVAL_DATE DATE "DD/MM/YYYY",
    TIPO_DOC CHAR(4000),
    NO_DOC CHAR(4000),
    FECHA_DOC DATE "DD/MM/YYYY",
    CODIGO_OC CHAR(4000),
    PRECIO CHAR(4000),
    TOTAL_USD CHAR(4000),
    FECHA_PAGO DATE "DD/MM/YYYY",
    FECHA_EFECTIVA DATE "DD/MM/YYYY",
    ABONOS CHAR(4000),
    CONCEPTO_NC CHAR(4000),
    PAST_DUE CHAR(4000),
    DIAS_CREDITO CHAR(4000)
    )
  )
  LOCATION ('PURE_DES.csv')
)
REJECT LIMIT UNLIMITED
;
  