drop table AGROSTG.PURE_CONTRATOS;
truncate table AGROSTG.PURE_CONTRATOS;


select *
from AGROSTG.PURE_CONTRATOS;

select to_char(last_ddl_time,'dd/mm/yyyy hh:mi:ss') from dba_objects where object_name = 'PURE_DESPACHOS'
;

CREATE TABLE AGROSTG.PURE_CONTRATOS
(
    ANO NUMBER,
    CLIENTE VARCHAR2(100 BYTE),
    TIPO_CONTRATO VARCHAR2(100 BYTE),
    PRODUCTO VARCHAR2(100 BYTE),
    TM_CONTRATO NUMBER,
    DIAS_CREDITO NUMBER,
    OPERACION VARCHAR2(100 BYTE),
    FECHA_CONTRATO DATE,
    JJOIN VARCHAR2(100 BYTE),
    TM_ORDEN NUMBER,
    CONTRATO_COD VARCHAR2(100 BYTE)
)
ORGANIZATION EXTERNAL (
  TYPE ORACLE_LOADER
  DEFAULT DIRECTORY google_sheets
  ACCESS PARAMETERS (
    RECORDS DELIMITED BY NEWLINE
    SKIP 1
    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
    MISSING FIELD VALUES ARE NULL
(
    ANO CHAR(4000),
    MES CHAR(4000),
    CLIENTE CHAR(4000),
    CODIGO_OC CHAR(4000),
    REF_EXTERNA CHAR(4000),
    FECHA_ORDEN DATE "DD/MM/YYYY",
    TIPO CHAR(4000),
    PRODUCTO CHAR(4000),
    PRECIO CHAR(4000),
    TOTAL_OC CHAR(4000),
    CONTRATO CHAR(4000),
    OBSERVACION CHAR(4000),
    TM_CONTRATO CHAR(4000),
    JJOIN CHAR(4000),
    TM_ORDEN CHAR(4000),
    CONTRATO_COD CHAR(4000)
    )
  )
  LOCATION ('PURE_ORD.csv')
)
REJECT LIMIT UNLIMITED
;
  