select * from AGROSTG.PALM_SALES_PLAN;

/*DROP*/
drop table AGROSTG.PALM_SALES_PLAN;
/*CREATE*/
CREATE TABLE AGROSTG.PALM_SALES_PLAN(
  FECHA DATE,
  CLIENTE VARCHAR2(100 BYTE),
  PRODUCTO VARCHAR2(100 BYTE),
  TM NUMBER
)
ORGANIZATION EXTERNAL (
  TYPE ORACLE_LOADER
  DEFAULT DIRECTORY google_sheets
  ACCESS PARAMETERS (
    RECORDS DELIMITED BY NEWLINE
    SKIP 1
    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
    MISSING FIELD VALUES ARE NULL
    (
      FECHA DATE "DD/MM/YYYY",
      CLIENTE,
      PRODUCTO,
      TM
    )
  )
  --LOCATION ('Countries1.txt','Countries2.txt')
  LOCATION ('SALESPLAN.csv')
)
--PARALLEL 5
REJECT LIMIT UNLIMITED;