select * from AGROSTG.PALM_ORDENES;

/*DROP*/
drop table AGROSTG.PALM_ORDENES;
/*CREATE*/
CREATE TABLE AGROSTG.PALM_ORDENES(
  ANO NUMBER, 
  MES VARCHAR2(100 BYTE), 
  CLIENTE VARCHAR2(100 BYTE), 
  CODIGO VARCHAR2(100 BYTE), 
  REF_EXTERNA VARCHAR2(100 BYTE), 
  FECHA_ORDEN DATE,
  TIPO_CONTRATO VARCHAR2(100 BYTE),
  PRODUCTO VARCHAR2(100 BYTE),
  PRECIO NUMBER,
  TOTAL_OC NUMBER,
  CONTRATO_COD VARCHAR2(100 BYTE)
)
ORGANIZATION EXTERNAL (
  TYPE ORACLE_LOADER
  DEFAULT DIRECTORY google_sheets
  ACCESS PARAMETERS (
    RECORDS DELIMITED BY NEWLINE
    SKIP 1
    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
    MISSING FIELD VALUES ARE NULL
    (
      ANO,
      MES,
      CLIENTE,
      CODIGO,
      REF_EXTERNA,
      FECHA_ORDEN DATE "DD/MM/YYYY",
      TIPO_CONTRATO,
      PRODUCTO,
      PRECIO,
      TOTAL_OC,
      CONTRATO_COD
    )
  )
  --LOCATION ('Countries1.txt','Countries2.txt')
  LOCATION ('ORDENES.csv')
)
--PARALLEL 5
REJECT LIMIT UNLIMITED;