--drop table AGROSTG.ONE_VOLUMEN
CREATE TABLE "AGROSTG"."ONE_VOLUMEN" 
   (	
   "SEMANA" NUMBER, 
	"CLIENTE" VARCHAR2(100 BYTE), 
	"PAIS_ORIGEN" VARCHAR2(100 BYTE), 
	"PTO_DESTINO" VARCHAR2(100 BYTE), 
	"ZONA_DESTINO" VARCHAR2(100 BYTE), 
	"TIPO_EMPAQUE" VARCHAR2(100 BYTE), 
	"TIPO_FRUTA" VARCHAR2(100 BYTE), 
	"CAJAS" NUMBER, 
	"LOADS" NUMBER
   )
  TABLESPACE "STAGE" ;