select * from AGROSTG.ONE_LOADS;

/*DROP*/
drop table AGROSTG.ONE_LOADS;
/*CREATE*/
CREATE TABLE AGROSTG.ONE_LOADS(
  MARCA VARCHAR2(100 BYTE), 
	PAIS_ORIGEN VARCHAR2(100 BYTE), 
	ZONA_ORIGEN VARCHAR2(100 BYTE), 
  SEMANA NUMBER, 
	FECHA_EMPAQUE DATE, 
	CONTENEDOR VARCHAR2(100 BYTE), 
	TRAZABILIDAD VARCHAR2(100 BYTE), 
	MARCHAMO VARCHAR2(100 BYTE), 
	TERMOGRAFO VARCHAR2(100 BYTE),
	CLIENTE VARCHAR2(100 BYTE), 
	NAVIERA VARCHAR2(100 BYTE), 
	PTO_DESTINO VARCHAR2(100 BYTE),
  DIA_ZARPE VARCHAR2(100 BYTE),
	EMPACADORA VARCHAR2(100 BYTE), 
  PLANTA VARCHAR2(100 BYTE), 
	TIPO_CAJA VARCHAR2(100 BYTE), 
	CAJAS NUMBER, 
	CABEZAL VARCHAR2(100 BYTE), 
	HORA_LLEGADA VARCHAR2(100 BYTE), 
	HORA_SALIDA VARCHAR2(100 BYTE), 
	HOROMETRO VARCHAR2(100 BYTE), 
	ZONA_DESTINO VARCHAR2(100 BYTE),
	ORIGEN_FRUTA VARCHAR2(100 BYTE), 
	PROVEEDOR VARCHAR2(100 BYTE), 
	PTO_ORIGEN VARCHAR2(100 BYTE),   
	TIPO_FRUTA VARCHAR2(100 BYTE), 
	BL VARCHAR2(100 BYTE),
	FACTURA VARCHAR2(100 BYTE), 
	FECHA_FACTURA DATE,  
	FAC_SHIPPER VARCHAR2(100 BYTE), 
	DEPEX VARCHAR2(100 BYTE), 
	POLIZA VARCHAR2(100 BYTE), 
	BOOKING VARCHAR2(100 BYTE), 
	BARCO_VIAJE VARCHAR2(100 BYTE), 
	ETA DATE, 
	DELIVERY_WEEK VARCHAR2(100 BYTE), 
	DELIVERY_DATE DATE, 
	DELIVERY_CLIENT VARCHAR2(100 BYTE),
	ESTADO VARCHAR2(100 BYTE),
  ISSUES VARCHAR2(100 BYTE),
  COMENTARIO VARCHAR2(400 BYTE)
)
ORGANIZATION EXTERNAL (
  TYPE ORACLE_LOADER
  DEFAULT DIRECTORY google_sheets
  ACCESS PARAMETERS (
    RECORDS DELIMITED BY NEWLINE
    SKIP 1
    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
    MISSING FIELD VALUES ARE NULL
    (
       MARCA CHAR(4000),
        PAIS_ORIGEN CHAR(4000),
        ZONA_ORIGEN CHAR(4000),
        SEMANA CHAR(4000),
        FECHA_EMPAQUE DATE "DD/MM/RR",
        CONTENEDOR CHAR(4000),
        TRAZABILIDAD CHAR(4000),
        MARCHAMO CHAR(4000),
        TERMOGRAFO CHAR(4000),
        CLIENTE CHAR(4000),
        NAVIERA CHAR(4000),
        PTO_DESTINO CHAR(4000),
        DIA_ZARPE CHAR(4000),
        EMPACADORA CHAR(4000),
        PLANTA CHAR(4000),
        CALIDAD CHAR(4000),
        TIPO_CAJA CHAR(4000),
        CAJAS CHAR(4000),
        CABEZAL CHAR(4000),
        HORA_LLEGADA CHAR(4000),
        HORA_SALIDA CHAR(4000),
        HOROMETRO CHAR(4000),
        ZONA_DESTINO CHAR(4000),
        ORIGEN_FRUTA CHAR(4000),
        PROVEEDOR CHAR(4000),
        PTO_ORIGEN CHAR(4000),
        TIPO_FRUTA CHAR(4000),
        BL CHAR(4000),
        FACTURA CHAR(4000),
        FECHA_FACTURA DATE "DD/MM/RR",
        FAC_SHIPPER CHAR(4000),
        DEPEX CHAR(4000),
        POLIZA CHAR(4000),
        BOOKING CHAR(4000),
        BARCO_VIAJE CHAR(4000),
        ETA DATE "DD/MM/RR",
        DELIVERY_WEEK CHAR(4000),
        DELIVERY_DATE DATE "DD/MM/RR",
        DELIVERY_CLIENT CHAR(4000),
        ESTADO CHAR(4000),
        ISSUES CHAR(4000),
        COMENTARIO CHAR(4000)
    )
  )
  --LOCATION ('Countries1.txt','Countries2.txt')
  LOCATION ('LOADS.csv')
)
--PARALLEL 5
REJECT LIMIT UNLIMITED;