--drop table AGROSTG.ONE_SHIP_RATES;
CREATE TABLE AGROSTG.ONE_SHIP_RATES
   (	
   "ANO" NUMBER, 
	"PAIS_ORIGEN" VARCHAR2(100 BYTE), 
	"NAVIERA" VARCHAR2(100 BYTE), 
	"PTO_DESTINO" VARCHAR2(100 BYTE), 
	"ZONA_DESTINO" VARCHAR2(100 BYTE),
	"CLIENTE" VARCHAR2(100 BYTE), 
	"DIAS_TRANSITO" NUMBER, 
  "RATE" NUMBER, 
  "THC" NUMBER, 
	"DIA_ZARPE" VARCHAR2(100 BYTE), 
	"DIA_ARRIBO" VARCHAR2(100 BYTE)
   )
  TABLESPACE "STAGE" ;