select * from AGROSTG.PALM_DESPACHOS;

/*DROP*/
drop table AGROSTG.PALM_DESPACHOS;
/*CREATE*/
CREATE TABLE AGROSTG.PALM_DESPACHOS(
  ANO NUMBER, 	
    SEMANA NUMBER, 
    EXTRACTORA VARCHAR2(100 BYTE), 
    CLIENTE VARCHAR2(100 BYTE), 
    PRODUCTO VARCHAR2(100 BYTE), 
    FECHA_DESPACHO DATE,
    PLACAS_T1 VARCHAR2(100 BYTE),
    TM_T1 NUMBER,
    ACIDEZ_T1 NUMBER,
    HUMEDAD_T1 NUMBER,
    PLACAS_T2 VARCHAR2(100 BYTE),
    TM_T2 NUMBER,
    ACIDEZ_T2 NUMBER,
    HUMEDAD_T2 NUMBER,
    TOTAL_TM NUMBER,  
    TIPO_DOC VARCHAR2(100 BYTE),
    NO_DOC VARCHAR2(100 BYTE), 
    FECHA_DOC DATE,
    MES_OC VARCHAR2(100 BYTE), 
    OC VARCHAR2(100 BYTE),  
    PRECIO NUMBER,
    TOTAL_USD NUMBER,
    FECHA_PAGO DATE,
    FECHA_EFECTIVA DATE, 
    CONCEPTO_NC VARCHAR2(100 BYTE),
    PAST_DUE NUMBER
)
ORGANIZATION EXTERNAL (
  TYPE ORACLE_LOADER
  DEFAULT DIRECTORY google_sheets
  ACCESS PARAMETERS (
    RECORDS DELIMITED BY NEWLINE
    SKIP 1
    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
    MISSING FIELD VALUES ARE NULL
    (
      ANO CHAR(4000),
  SEMANA CHAR(4000),
  EXTRACTORA CHAR(4000),
  CLIENTE CHAR(4000),
  PRODUCTO CHAR(4000),
  FECHA_DESPACHO DATE "DD/MM/YYYY",
  PLACAS_T1 CHAR(4000),
  TM_T1 CHAR(4000),
  ACIDEZ_T1 CHAR(4000),
  HUMEDAD_T1 CHAR(4000),
  PLACAS_T2 CHAR(4000),
  TM_T2 CHAR(4000),
  ACIDEZ_T2 CHAR(4000),
  HUMEDAD_T2 CHAR(4000),
  TOTAL_TM CHAR(4000),
  TIPO_DOC CHAR(4000),
  NO_DOC CHAR(4000),
  FECHA_DOC DATE "DD/MM/YYYY",
  MES_OC CHAR(4000),
  OC CHAR(4000),
  PRECIO CHAR(4000),
  TOTAL_USD CHAR(4000),
  FECHA_PAGO DATE "DD/MM/YYYY",
  FECHA_EFECTIVA DATE "DD/MM/YYYY",
  CONCEPTO_NC CHAR(4000),
  PAST_DUE CHAR(4000)
    )
  )
  --LOCATION ('Countries1.txt','Countries2.txt')
  LOCATION ('PIPAS.csv')
)
--PARALLEL 5
REJECT LIMIT UNLIMITED;