select * from AGROSTG.PALM_CONTRATOS_DET;

/*DROP*/
drop table AGROSTG.PALM_CONTRATOS_DET;
/*CREATE*/
CREATE TABLE AGROSTG.PALM_CONTRATOS_DET(
  CONTRATO_COD VARCHAR2(100 BYTE),
  MES VARCHAR2(100 BYTE),
  FECHA_INI DATE,
  FECHA_FIN DATE,
  TM NUMBER
)
ORGANIZATION EXTERNAL (
  TYPE ORACLE_LOADER
  DEFAULT DIRECTORY google_sheets
  ACCESS PARAMETERS (
    RECORDS DELIMITED BY NEWLINE
    SKIP 1
    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
    MISSING FIELD VALUES ARE NULL
    (
      CONTRATO_COD,
      MES,
      FECHA_INI DATE "DD/MM/YYYY",
      FECHA_FIN DATE "DD/MM/YYYY",
      TM
    )
  )
  --LOCATION ('Countries1.txt','Countries2.txt')
  LOCATION ('CONTRATOS_DET.csv')
)
--PARALLEL 5
REJECT LIMIT UNLIMITED;